### PR TITLE
React 0.14.0

### PR DESCRIPTION
**Pull request by bkniffler**

### CODE REVIEW

**Comment by wangzuo** [comment]
wow, thanks but lets wait for the release now..

**Comment by bkniffler** [comment]
Could you at least merge the changes on the package.json? This will not break anything and allow usage with 0.14.0. The other changes are not critical and thus do not need to be merged yet, as react will only throw warnings.

**Comment by wangzuo** [comment]
`var dom = this.refs.inner;` maybe broken ?

**Comment by wangzuo** [comment]
Sounds good, its available in `2.2.2` now. Thanks.

**Comment by bkniffler** [comment]
Thanks mate, excellent work on this library btw!

**Pull request closed without merging**
